### ISSUE TITLE
What is the purpose?

### ISSUE THREAD

**Issue by lpiob** [terraform-aws-modules/terraform-aws-sqs#19]
What is the purpose of using a module that creates only one resource?

Why would I want to use:
```
module "users_unencrypted" {
  source = "https://github.com/terraform-aws-modules/terraform-aws-sqs/"

  name = "users-unencrypted"
}
```

When I could just declare the resource directly:

```
resource "aws_sqs_queue" "users_unencrypted" {
  name = "users-unencrypted"
}
```

**Comment by antonbabenko** [comment]
There are several reasons:
1. Module can be versioned as a whole, but resource can't.
2. Terragrunt uses modules natively
