### ISSUE TITLE
Hight through-put fifo queue parameters have to be enabled in this resource

### ISSUE THREAD

**Issue by sidda-dandu** [terraform-aws-modules/terraform-aws-sqs#31]
## Additional context

Hello, Could you please enable the high throughput fifo queue parameters in a resource so that we could able to make use of them through module call?
i.e.  `deduplication_scope        = "messageGroup"`
      `fifo_throughput_limit      = "perMessageGroupId"`

**Comment by antonbabenko** [comment]
Hi! Pull request is welcome.
