### ISSUE TITLE
SQS Queue URL Output

### ISSUE THREAD

**Issue by salyateem13** [terraform-aws-modules/terraform-aws-sqs#36]
## Is your request related to a new offering from AWS?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#attributes-reference

## Is your request related to a problem? Please describe.
I'm always frustrated when I need to use data sources for resources created in the same terraform script. Thanks for maintaining great AWS modules :0

## Describe the solution you'd like.
Add Queue Url from resource output as module output

## Describe alternatives you've considered.
Use SQS data source to retrieve URL

**Comment by antonbabenko** [comment]
There is already `sqs_queue_id` output returned by this module which is the same as `url`. https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/outputs.tf#L1-L10
