### ISSUE TITLE
SSE-SQS strategy missing

### ISSUE THREAD

**Issue by jycamier** [terraform-aws-modules/terraform-aws-sqs#37]
There's 2 ways to encrypte SQS : 
- SSE-SQS with a simple `sqs_managed_sse_enabled  = true`
- SSE-KMS (already available in the module)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#server-side-encryption-sse

It miss the first one.

**Comment by mzupan** [comment]
I created #39

**Comment by juan-vg** [comment]
This should be reopened. Now the queues are being created with server-side encryption by default, and there's no way to manage that

**Comment by antonbabenko** [comment]
Maintainers have other things (work and modules), too. Merged now.
