### ISSUE TITLE
Something is wrong with your pinning

### ISSUE THREAD

**Issue by rlewkowicz** [terraform-aws-modules/terraform-aws-sqs#38]
Your new version adds redrive support. Pinned to 3.2, I now get errors regarding redrive. 

I haven't had time to explore this. 

on .terraform/modules/etlv3-idplus-sqs-prod/main.tf line 14, in resource "aws_sqs_queue" "this":
```
  redrive_allow_policy        = var.redrive_allow_policy
 ```
An argument named "redrive_allow_policy" is not expected here.

**Comment by antonbabenko** [comment]
Which version of Terraform AWS provider are you using (try running `terraform init -upgrade` to upgrade it)?

**Comment by rlewkowicz** [comment]
Sorry, I think maybe my pin was wrong? I left the v out and maybe it was just grabbing latest
