### ISSUE TITLE
KMS Key: Conflicting configuration arguments after introduction of `sqs_managed_sse_enabled`

### ISSUE THREAD

**Issue by bendehaan** [terraform-aws-modules/terraform-aws-sqs#40]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Since module version 3.4.0, with the introduction of the variable `sqs_managed_sse_enabled` and associated logic, module configurations where a KMS key is specified error out with "conflicting configuration arguments"

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v3.4.0

- Terraform version: v1.3.1

- Provider version(s): AWS v4.33.0
```
+ provider registry.terraform.io/hashicorp/aws v4.33.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

## Reproduction Code [Required]

```
module "users_encrypted" {
  source = "../../"

  name_prefix = "users-encrypted-"

  kms_master_key_id = aws_kms_key.this.id

  tags = {
    Secure = "true"
  }
}
```

1. Create an SQS queue with a specified KMS key. (using the examples: `tf init && tf apply -target='module.users_encrypted'`)

## Expected behavior

The module creates an SQS queue encrypted with the specified Key ARN.

## Actual behavior

The apply errors out with "`Error: Conflicting configuration arguments`"

### Terminal Output Screenshot(s)

```
│ Error: Conflicting configuration arguments
│ 
│   with module.users_encrypted.aws_sqs_queue.this[0],
│   on ../../main.tf line 20, in resource "aws_sqs_queue" "this":
│   20:   sqs_managed_sse_enabled           = var.sqs_managed_sse_enabled
│ 
│ "sqs_managed_sse_enabled": conflicts with kms_master_key_id
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with module.users_encrypted.aws_sqs_queue.this[0],
│   on ../../main.tf line 21, in resource "aws_sqs_queue" "this":
│   21:   kms_master_key_id                 = var.sqs_managed_sse_enabled ? null : var.kms_master_key_id
│ 
│ "kms_master_key_id": conflicts with sqs_managed_sse_enabled
```

## Additional context

N.A.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.4.1 :tada:
