### ISSUE TITLE
dlq_kms_master_key_id is not working

### ISSUE THREAD

**Issue by akath19** [terraform-aws-modules/terraform-aws-sqs#48]
## Description

Setting value `dlq_kms_master_key_id` creates a dql queue with SQS Manager SSE key and doesn't use the provided KMS key, setting  `dlq_sqs_managed_sse_enabled = false` creates Conflicting configuration as described in #40.

Checking CloudTrail events shows that DLQ is created with `"SqsManagedSseEnabled": "true"` no matter what variables are chosen for KMS key.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 4.0.0

- Terraform version:
`Terraform v1.3.6`
- Provider version(s): 
`provider registry.terraform.io/hashicorp/aws v4.48.0`

## Reproduction Code [Required]

```
terraform {
  required_providers {
    aws = {
      version = "4.48.0"
    }
  }
}

provider "aws" {
  region = "{region}"
}

module "kms" {
  source = "terraform-aws-modules/kms/aws"
  version = "1.3.0"

  description = "repro key"
  key_usage = "ENCRYPT_DECRYPT"
}

module "queue" {
  source  = "terraform-aws-modules/sqs/aws"
  version = "4.0.0"

  name = "repro-queue"

  create_dlq = true

  kms_master_key_id = module.kms.key_id
  dlq_kms_master_key_id = module.kms.key_id
}
```

1. Create SQS queue with DLQ and KMS key

## Expected behavior

Module creates a DLQ queue with SSE-KMS encryption with the provided key instead of SSE-SQS

## Actual behavior

Module creates a DLQ queue with SSE-SQS encryption and ignores provided KMS key

### Terminal Output Screenshot(s)

Plan showing key is not used, attribute `kms_master_key_id` exists in `this` queue but not in `dlq`

![sqs-bug](https://user-images.githubusercontent.com/3260715/210860684-edea2658-7bc6-4775-b84f-e6412601f3aa.png)

## Additional context

Region for testing is GovCloud

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.1 :tada:
