### ISSUE TITLE
Allow `redrive_policy` to be null

### ISSUE THREAD

**Issue by bspammer** [terraform-aws-modules/terraform-aws-sqs#49]
## Is your request related to a problem? Please describe.
When setting `redrive_policy` to be `null`, I get the following error:

```
count = var.create && !var.create_dlq && length(var.redrive_policy) > 0 ? 1 : 0
    │ while calling length(value)
    │ var.redrive_policy is null
Invalid value for "value" parameter: argument must not be null.
```

## Describe the solution you'd like.
Something like https://github.com/bspammer/terraform-aws-sqs/compare/195b0bccc44ff908e36cc425aeeb7547db7c798e..20bf68531bb59a056eb46a95aa5dc09231088795

## Describe alternatives you've considered.

I have tried using `{}` instead of null, but that causes terraform's type system to assume that the other branch of a ternary expression has strings for all its values. For example

```
module "queue" {
  source  = "terraform-aws-modules/sqs/aws"
  version = "4.0.0"

  redrive_policy = var.enable_default_redrive_policy ? {
    deadLetterTargetArn = "arn:aws:sqs:eu-west-1:000000000000:queue",
    maxReceiveCount     = 3
  } : {}

}
```

causes terraform to assume that the type of `maxReceiveCount` is string, which then causes issues because the json encoded version of the object no longer matches what is provided by AWS.

**Comment by bryantbiggs** [comment]
I'm not following, you are saying that the following throws errors?

```hcl
module "queue" {
  source  = "terraform-aws-modules/sqs/aws"
  version = "4.0.0"

  redrive_policy = {}
}
```

**Comment by bspammer** [comment]
However the same ternary with `null` instead of `{}` works great, which is why it would be great to allow it.

**Comment by bryantbiggs** [comment]
```hcl
module "queue" {
  source  = "terraform-aws-modules/sqs/aws"
  version = "4.0.0"

  redrive_policy = {for k,v in {
    deadLetterTargetArn = "arn:aws:sqs:eu-west-1:000000000000:queue",
    maxReceiveCount     = 3
  }: k => v if var.enable_default_redrive_policy }
}
```

**Comment by bspammer** [comment]
That's a cool solution, thanks.

**Comment by bryantbiggs** [comment]
closing with solution provided above
