### ISSUE TITLE
DLQ naming convention is wrong

### ISSUE THREAD

**Issue by amitkml** [terraform-aws-modules/terraform-aws-sqs#50]
## Description

DLQ is getting created wrongly and hence failing with error "invalid queue name"

If your request is for a new feature, please use the `Feature request` template.

## Versions
I am using latest version of this module.

## Existing code

I have the SQS code as follows which is having DLQ emabled but the DLQ is getting created wrongly.

`
module "sqs_insight_classification_ner_logging" {
  source                      = "terraform-aws-modules/sqs/aws"
  name                        = "${local.service_name}-sqs_insight_classification_ner_logging-${var.environment_bu_id}.fifo"
  tags                        = local.services_tags
  fifo_queue                  = true
  content_based_deduplication = true
  visibility_timeout_seconds  = 60 ## This has to be same as caller lambda question_asked_semsim
   # Enable creation of dead letter queue
  create_dlq = true
  redrive_policy = {
    # default is 5 for this module
    maxReceiveCount = 2
  }
}

`

## Expected behavior

DLQ should be created correctly.

## Actual behavior
You can see here the DLQ naming is wrong.

│ Error: invalid queue name: re-them-ml-backend-sqs_insight_classification_ner_logging-dev.fifo-dlq.fifo
│
│   with module.sqs_insight_classification_ner_logging.aws_sqs_queue.dlq[0],
│   on .terraform\modules\sqs_insight_classification_ner_logging\main.tf line 122, in resource "aws_sqs_queue" "dlq":
│  122: resource "aws_sqs_queue" "dlq" {
│
╵
╷
│ Error: invalid queue name: re-them-ml-backend-sqs_transcript_item_put-dev.fifo-dlq.fifo
│
│   with module.sqs_transcript_item_put.aws_sqs_queue.dlq[0],
│   on .terraform\modules\sqs_transcript_item_put\main.tf line 122, in resource "aws_sqs_queue" "dlq":
│  122: resource "aws_sqs_queue" "dlq" {

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.1 :tada:
