### ISSUE TITLE
Unable to set condition on policy statement (following the example)

### ISSUE THREAD

**Issue by pballester** [terraform-aws-modules/terraform-aws-sqs#53]
In the example provided in the README the attribute is called `condition`:
https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/README.md?plain=1#L122

But in the module code the attribute name is different https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/main.tf#L70.

Regards.

**Comment by micbegin** [comment]
A proper example is given at https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/README.md?plain=1#L84 the one at https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/README.md?plain=1#L122 should be fixed since it is simply ignored by the module.
