### ISSUE TITLE
sqs policy document support for "statement.value.condition"

### ISSUE THREAD

**Issue by Roxyrob** [terraform-aws-modules/terraform-aws-sqs#56]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

Not sure which introduced this, probably from early versions.

## Is your request related to a problem? Please describe.
Hi,
thank you for your excellent code. I meet an issue described below, not sure if I'm missing something.

In main.tf in data source **data "aws_iam_policy_document" "this"** I tried to pass to **var.queue_policy_statements** a mix of manually defined and data source derived policies:

<pre>
data "aws_iam_policy_document" "custom1" {
  version = "2012-10-17"
  statement {
    sid     = "SNSPublish"
    effect  = "Allow"
    actions = ["sqs:SendMessage"]

    principals {
      type        = "Service"
      identifiers = ["sns.amazonaws.com"]
    }

    <b>condition</b> {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [arn:qws:...]
    }
  }
}

module "sqs" {
  source  = "terraform-aws-modules/sqs/aws"
  ...
  <b>queue_policy_statements</b> = concat(
    data.aws_iam_policy_document.custon1.statement,
    [
      {
        actions = [
          "sqs:DeleteMessage",
          "sqs:GetQueueUrl",
          "sqs:ReceiveMessage",
          "sqs:SendMessage",
        ]
        principals = [
          {
            type = "AWS"
            identifiers = [
             "arn:aws:iam::xxxxxxxxxxxxx:role/app1",
             "arn:aws:iam::xxxxxxxxxxxxx:role/app2"
            ]
          },
        ]
      },
    ]
  )
}
</pre>

but **condition** from data source will be missed on final policy attached to sqs queue as **data "aws_iam_policy_document" "this"** parse "**conditions**" instead of "**condition**" here:

<pre>
dynamic "condition" {
        for_each = try(statement.value.<b>conditions</b>, [])

        content {
          test     = condition.value.test
          values   = condition.value.values
          variable = condition.value.variable
        }
</pre> 

## Describe the solution you'd like.
sqs module should parse standard data.aws_iam_policy_document output (using **condition**)

## Describe alternatives you've considered.
Can you support **condition** instead of **conditions** (or both) or I have to write code to convert data.aws_iam_policy_document output to match actual module parsing  ?

**Comment by bryantbiggs** [comment]
if you are trying to pass a document, you would pass `data.aws_iam_policy_document.custon1.json` to `source_queue_policy_documents`

if you want to specify statements, bypassing the use of the document you just state them directly

**Comment by Roxyrob** [comment]
Hi @bryantbiggs,
how can this suggestion solve the issue ?

aws_iam_policy_document output "**condition**" on any output type (.json, .statement) the module search for "**conditions**".

Also it seems that .json format is incompatible with syntax used in this module.

**Comment by bryantbiggs** [comment]
```hcl
module "sqs" {
  source  = "terraform-aws-modules/sqs/aws"
  ...
  source_queue_policy_documents = data.aws_iam_policy_document.custon1.json
  queue_policy_statements = [
      {
        actions = [
          "sqs:DeleteMessage",
          "sqs:GetQueueUrl",
          "sqs:ReceiveMessage",
          "sqs:SendMessage",
        ]
        principals = [
          {
            type = "AWS"
            identifiers = [
             "arn:aws:iam::xxxxxxxxxxxxx:role/app1",
             "arn:aws:iam::xxxxxxxxxxxxx:role/app2"
            ]
          },
        ]
      },
    ]
}
```

**Comment by Roxyrob** [comment]
Got it !
Thank you.

PS: why anyway not persing "condition" ? This would make the module more flexible and more consistent with standard aws_iam_policy_document output format.

**Comment by Roxyrob** [comment]
For the sake of completeness, source_queue_policy_documents expect **list(string)**:

<pre>
...
source_queue_policy_documents = <b>[</b>data.aws_iam_policy_document.custon1.json<b>]</b>
...
</pre>
