### ISSUE TITLE
 make resource "aws_sqs_queue_redrive_allow_policy" "dlq" 

### ISSUE THREAD

**Issue by jebbens** [terraform-aws-modules/terraform-aws-sqs#59]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: aws_sqs_queue_redrive_allow_policy was introduced in AWS provider in 4.31.0

## Is your request related to a problem? Please describe.

Some AWS regions do not support redrive allow policies on dead letter queues (DLQ). Thus, when deploying a stack that includes a DLQ in one of these regions, the stack will fail because Terraform attempts to create `resource "aws_sqs_queue_redrive_allow_policy" "dlq"` due to `var.create_dlq = true`.

## Describe the solution you'd like.

Users should be able to create a DLQ without a redrive allow policy. This could be implemented by creating a `var.create_redrive_allow_policy_dlq` that could be used in the conditional statement for the count associated with the `"aws_sqs_queue_redrive_allow_policy" "dlq"` resource, i.e. `count = var.create && var.create_dlq && length && var.create_redrive_allow_policy_dlq ? 1 : 0`. The variable could be set with `default = true` to maintain backward compatibility.

## Describe alternatives you've considered.

This could also be implemented by creating a `var.redrive_allow_policy_dlq` (similar to `var.redrive_allow_policy`) where the length of the value could be used in the conditional statement for the count associated with the `"aws_sqs_queue_redrive_allow_policy" "dlq"` resource, i.e. `count = var.create && var.create_dlq && length(var.redrive_allow_policy_dlq) > 0 ? 1 : 0`. But, this would require removing the default policy included in the resource and it would be up to the user to specify the entire policy including what was previously done for them.

**Comment by daniel-milemarker** [comment]
I am running into this same issue on a project we are working on.

module.sqs.aws_sqs_queue_policy.dlq[0]: Creating...
```
╷
│ Error: setting SQS Queue (https://sqs.us-west-2.amazonaws.com/<accuont>/<queue-name>-dlq) attribute (Policy): InvalidAttributeValue: Invalid value for the parameter Policy.
│       status code: 400, request id: 
│
│   with module.sqs.aws_sqs_queue_policy.dlq[0],
│   on .terraform\modules\sqs\main.tf line 202, in resource "aws_sqs_queue_policy" "dlq":
│  202: resource "aws_sqs_queue_policy" "dlq" {
│
╵
```

@jebbens is there a workaround that you've found for this?

**Comment by jebbens** [comment]
Sorry for the delayed response. I ended up creating a separate queue resource to be used as a DLQ, whose ARN is referenced as the `deadLetterTargetArn` for the other "source" queues.

**Comment by jebbens** [comment]
Completed in #60
