### ISSUE TITLE
example of attached policy

### ISSUE THREAD

**Issue by vitbyst** [terraform-aws-modules/terraform-aws-sqs#7]
Is there an example of attached policy JSON? Not clear to me how the policy can refer the resource the module creates.

e.g. 

{
  "Version": "2012-10-17",
  "Id": "sqspolicy",
  "Statement": [
    {
      "Sid": "First",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:SendMessage",
      "Resource": "${aws_sqs_queue.q.arn}",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "${aws_sns_topic.example.arn}"
        }
      }
    }
  ]
}
POLICY

**Comment by asilvanovich** [comment]
```hcl
  policy = <<EOF
{
  "Version": "2008-10-17",
  "Id": "My sqs policy",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::your_account:root"
      },
      "Action": "SQS:*",
      "Resource": "queue_arn"
    }
  ]
}
EOF
```
If someone needs it
